### ISSUE TITLE
Auto Sync

### ISSUE THREAD

**Issue by jhealey5** [mattgrayisok/craft-list-builder#4]
It doesn't seem to sync to sendgrid after 10 subscriptions, even after visiting the control panel.

Would it be possible to get the option to automatically sync for each subscription and/or specify a number? We don't expect a lot of traffic and we don't expect our client to have to manually sync the subscriptions, or install another plugin / cron task just to handle syncing.

Craft Pro 3.0.37
List Builder 1.0.3
PHP 7.1.13

Cheers.

**Comment by mattgrayisok** [comment]
Hi @jhealey5 

Is the manual sync working for you currently? It's just the queuing of a sync task after 10 subs that your having problems with?

I was considering adding in an option to reduce the number subscriptions required before a sync task is queued so I'll get that added to the plugin settings and release in the next version over the next few days.

**Comment by mattgrayisok** [comment]
After a quick review I can see a circumstance in which the 'every 10th' task scheduling will fail to happen.

Adding a fix to be released shortly.

**Comment by mattgrayisok** [comment]
I've added both a fix for what I think was going wrong with the auto queuing of a sync task and also the ability to set the number of subscriptions which should trigger a sync task to v1.0.4 which I just released.

I'll close this for now. Please re-open if you continue to have any problems.

Cheers

**Comment by jhealey5** [comment]
@mattgrayisok Sorry, bit of a late response, but thanks that's brilliant mate! :)

Cheers.
