### ISSUE TITLE
IE 11 Support?

### ISSUE THREAD

**Issue by jpcarpenter** [mattgrayisok/craft-list-builder#5]
Does this plugin support IE11 at all? There seems to be a `forEach` loop within the `listbuilder.js` file that IE11 keeps complaining about. Would be great if a polyfill could be added to accommodate for this!

![Screen Shot 2019-06-05 at 9 40 57 AM](https://user-images.githubusercontent.com/5934150/58965656-8e9c2800-8776-11e9-822e-85ea2a2ec068.png)

**Comment by mattgrayisok** [comment]
Thanks for flagging. I've just pushed v1.0.5 which swaps out any `forEach` for old-school `for` loops. I had a scan through the rest of the non-cp code and couldn't see anything else in there that might upset IE11 so it should be all good now.

Let me know if you encounter any other issues :+1:
